apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: lock
spec:
  version: {{ .TagName }}
  homepage: https://github.com/chaosinthecrd/kube-lock
  shortDescription: A pane of glass between you and your Kubernetes clusters
  description: An intermediary between you and kubectl, allowing you to lock/unlock contexts.
  caveats: must alias `kubectl` to kubectl-lock kubectl in `.bashrc`/`.zshrc` (e.g., alias kubectl='kubectl-lock kubectl --')
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/chaosinthecrd/kube-lock/releases/download/{{ .TagName }}/kube-lock_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-lock
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/chaosinthecrd/kube-lock/releases/download/{{ .TagName }}/kube-lock_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
    bin: kubectl-lock
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/chaosinthecrd/kube-lock/releases/download/{{ .TagName }}/kube-lock_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-lock
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/chaosinthecrd/kube-lock/releases/download/{{ .TagName }}/kube-lock_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
    bin: kubectl-lock.exe
